- name: Python
  logo: python
  url: https://www.python.org/
  color: "#3C78A9"
  projects:
    - url: https://github.com/amaan-mohib/pdf-maker
    - url: https://github.com/amaan-mohib/mover
    - url: https://github.com/amaan-mohib/Movie-Icons

- name: JavaScript
  logo: javascript
  url: https://www.javascript.com/
  color: "#F7DF1E"
  projects:
    - url: https://github.com/amaan-mohib/storieshub
    - url: https://github.com/amaan-mohib/d-financely
    - url: https://github.com/amaan-mohib/d-financely-api
    - url: https://github.com/amaan-mohib/deltasudoku
    - url: https://github.com/amaan-mohib/stacker
    - url: https://github.com/amaan-mohib/Quinch-Web

- name: Java
  logo: java
  url: https://www.java.com/
  color: "#007396"
  projects:
    - url: https://github.com/amaan-mohib/Quinch
    - url: https://github.com/amaan-mohib/Downloader

- name: React Native
  logo: react
  url: https://reactnative.dev/
  color: "#61DAFB"
  projects:
    - url: https://github.com/amaan-mohib/MovieOps
    
- name: Flask
  logo: flask
  url: https://flask.palletsprojects.com/
  color: "#000000"
  projects:
    - url: https://github.com/amaan-mohib/portfolioid
